// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnlnjemzhhcnswptienk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubG5qZW16aGhjbnN3cHRpZW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzA2MDMsImV4cCI6MjA2MTM0NjYwM30.TSuqdSWli3VkP-17Q_5MHnIFU_pWETr6Ky4SBF0k88s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);